export const GET_SEARCH_MOVIES_REQUEST = "GET_SEARCH_MOVIES_REQUEST" as const;
export const GET_SEARCH_MOVIES_SUCCESS = "GET_SEARCH_MOVIES_SUCCESS" as const;
export const GET_SEARCH_MOVIES_FAILURE = "GET_SEARCH_MOVIES_FAILURE" as const;

export const GET_DETAILS_MOVIE_REQUEST = "GET_DETAILS_MOVIE_REQUEST" as const;
export const GET_DETAILS_MOVIE_SUCCESS = "GET_DETAILS_MOVIE_SUCCESS" as const;
export const GET_DETAILS_MOVIE_FAILURE = "GET_DETAILS_MOVIE_FAILURE" as const;

export const RESET_SEARCH_MOVIES = "RESET_SEARCH_MOVIES" as const;
